spring.application.name=citas
spring.datasource.url=jdbc:sqlite:citas_medicas.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always